CREATE TABLE [dbo].[Screening]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
	[MovieId] INT NOT NULL FOREIGN KEY REFERENCES Movie(Id),
	[TheaterId] INT NOT NULL FOREIGN KEY REFERENCES Theater(Id),
	[ScreeningDate ★] DATETIME NOT NULL
)
